// <auto-generated />
using System;
using FPVDevelopment.Components.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FPVDevelopment.Migrations
{
    [DbContext(typeof(FPVDbContext))]
    partial class FPVDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FPVDevelopment.Components.Data.Models.CompletedRun", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DroneID")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("Time")
                        .HasColumnType("time");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CourseID");

                    b.HasIndex("DroneID");

                    b.HasIndex("UserID");

                    b.ToTable("CompletedRuns");
                });

            modelBuilder.Entity("FPVDevelopment.Components.Data.Models.Course", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<int>("MapID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MapID");

                    b.HasIndex("UserID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("FPVDevelopment.Components.Data.Models.Drone", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SimID")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SimID");

                    b.HasIndex("UserID");

                    b.ToTable("Drones");
                });

            modelBuilder.Entity("FPVDevelopment.Components.Data.Models.Map", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SimID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SimID");

                    b.HasIndex("UserID");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("FPVDevelopment.Components.Data.Models.Sim", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Sims");
                });

            modelBuilder.Entity("FPVDevelopment.Components.Data.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserLevel")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FPVDevelopment.Components.Data.Models.CompletedRun", b =>
                {
                    b.HasOne("FPVDevelopment.Components.Data.Models.Course", "Course")
                        .WithMany("CompletedRuns")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FPVDevelopment.Components.Data.Models.Drone", "Drone")
                        .WithMany("CompletedRuns")
                        .HasForeignKey("DroneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FPVDevelopment.Components.Data.Models.User", "User")
                        .WithMany("CompletedRuns")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Drone");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FPVDevelopment.Components.Data.Models.Course", b =>
                {
                    b.HasOne("FPVDevelopment.Components.Data.Models.Map", "Map")
                        .WithMany("Courses")
                        .HasForeignKey("MapID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FPVDevelopment.Components.Data.Models.User", "User")
                        .WithMany("Courses")
                        .HasForeignKey("UserID");

                    b.Navigation("Map");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FPVDevelopment.Components.Data.Models.Drone", b =>
                {
                    b.HasOne("FPVDevelopment.Components.Data.Models.Sim", null)
                        .WithMany("Drones")
                        .HasForeignKey("SimID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FPVDevelopment.Components.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FPVDevelopment.Components.Data.Models.Map", b =>
                {
                    b.HasOne("FPVDevelopment.Components.Data.Models.Sim", "Sim")
                        .WithMany("Maps")
                        .HasForeignKey("SimID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FPVDevelopment.Components.Data.Models.User", "User")
                        .WithMany("Maps")
                        .HasForeignKey("UserID");

                    b.Navigation("Sim");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FPVDevelopment.Components.Data.Models.Course", b =>
                {
                    b.Navigation("CompletedRuns");
                });

            modelBuilder.Entity("FPVDevelopment.Components.Data.Models.Drone", b =>
                {
                    b.Navigation("CompletedRuns");
                });

            modelBuilder.Entity("FPVDevelopment.Components.Data.Models.Map", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("FPVDevelopment.Components.Data.Models.Sim", b =>
                {
                    b.Navigation("Drones");

                    b.Navigation("Maps");
                });

            modelBuilder.Entity("FPVDevelopment.Components.Data.Models.User", b =>
                {
                    b.Navigation("CompletedRuns");

                    b.Navigation("Courses");

                    b.Navigation("Maps");
                });
#pragma warning restore 612, 618
        }
    }
}
